config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Root path is defined in config/initializers/high_voltage.rb

  get "/r/:token", controller: :redirects, action: :show, as: :redirect
  resources :links, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates(
    :url,
    presence: true,
    url: true
  )

  has_many :visits
  belongs_to :user
end

app/models/redirect_process.rb
class RedirectProcess

  def initialize(token)
    @token = token
  end

  def call
    record_visit
    link.url
  end

  private
  attr_reader :token

  def link
    @link ||= Link.find_by(token: token) || UnknownLink
  end

  def record_visit
    link.visits.create unless link == UnknownLink
  end
end

app/models/unknown_link.rb
module UnknownLink
  def self.url
    "/404.html"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :links
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to(
    :link,
    counter_cache: true
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_login

  def destroy
    link = current_user.links.find(params[:id])
    if link.destroy
      flash[:notice] = t("links.delete.deleted_link", url: link.url)
    end
    redirect_to links_path
  end

  def create
    service = LinkCreateService.new(user: current_user,
                                    link_attributes: link_attributes)
    @link = service.link
    if service.create
      redirect_to links_path
    else
      flash[:error] = service.error_messages
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @links = current_user.links
  end

  def new
    @link = Link.new
  end

  private
  def link_attributes
    params.
      require(:link).
      permit(:url)
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ActionController::Base
  def show
    redirect_to RedirectProcess.new(params[:token]).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <title><%= page_title %></title>
</head>
<body class="<%= body_class %>">

  <header class="navigation" role="banner">
    <div class="navigation-wrapper">
      <a href="javascript:void(0)" class="logo">
        <%= image_tag "srink_ray.png", alt: "shrink-ray" %>
      </a>
      <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu"><%= t(".menu") %></a>
      <nav role="navigation">
        <ul id="js-navigation-menu" class="navigation-menu show">
          <li class="nav-link"><%= link_to t(".about"), page_path("about") %></li>
          <% if signed_in? %>
            <li class="nav-link"><%= link_to t(".links"), links_path %>"></li>
          <% else %>
            <li class="nav-link"><%= link_to t(".sign_in"), sign_in_path %></li>
          <% end %>
        </ul>
      </nav>
      <div class="navigation-tools">
        <% if signed_in? %>
          <%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "sign-out" %>
        <% end %>
      </div>
    </div>
  </header>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>" class="flash-<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for link do |f|  %>
  <%= f.input :url, as: :string, label:t(".url"), required: true %>
  <%= f.button :submit, t(".submit") %>
<% end %>

app/views/links/index.html.erb
<%= link_to t(".new_link"), new_link_path  %>

<table class="tables">
  <thead>
    <tr>
      <th>Original</th>
      <th>Srink URL</th>
      <th>Visits</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr id="<%= "link-#{link.id}" %>">
        <td><%= link.url %></td>
        <td><a href="<%= redirect_url(link.token) %>" data-turbolinks="false"><%= redirect_url(link.token) %></a></td>
        <td><%= link.visits.size %></td>
        <td><%= button_to "Delete", link_path(link), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/new.html.erb
<%= render partial: "form", locals: {link: @link} %>

app/views/pages/about.html.erb
<article>
<section id="welcome">
  <h1><%= t('.welcome') %></h1>
  <p>
  <%= t(".intro") %>
  </p>
</section>
<section id="source">
<h2><%= t(".source") %></h2>
<p>
<%= t(".about_source") %>
<a href="http://www.github.com/indiebrain/srink">
  http://www.github.com/indiebrain/srink
</a>
</p>
</section>
<section id="author">
  <h2><%= t('.author') %></h2>
  <p>
    <%= t(".about_author") %>
  </p>
  <ul>
    <li><a href="http://www.aaronkuehler.com"><%= fa_icon "globe", class: "fa-fw", text: "Website" %></li>
    <li><a href="http://www.github.com/indiebrain"><%= fa_icon "github", class: "fa-fw", text: "Github" %></a></li>
    <li><a href="http://www.twitter.com/indiebrain"><%= fa_icon "twitter", class: "fa-fw", text: "Twitter" %></li>
    <li><a href="https://www.linkedin.com/in/aaronkuehler"><%= fa_icon "linkedin", class: "fa-fw", text: "LinkedIn" %></li>
  </ul>
  </p>
</section>
</article>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>